# Generated by Django 5.1.4 on 2024-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
