# Generated by Django 5.1.4 on 2024-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0002_alter_buyer_name_alter_game_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
